create database retail;
create table brands (Brand_id int,Brand_name text);
create table categories(Category_id int,Category_name text);
create table customers(Customer_id int,First_name text,Last_name text,Phone bigint,Email text,Street text,
City text,State text,Zip_code int);
create table order_items(Order_id int,Item_id int,Product_id int,Quantity int, List_price double,
Discount double,Total_price double,Product_name text,Category_id int,Category_name text);
create table orders(Order_id int,Customer_id int,Order_status int,Order_date date,Required_date date,
Shipped_date date,Store_id int,staff_id int,orderstatus text);
create table products (Product_id int,Product_name text,Brand_id int,Category_id int,Model_year int,List_price double);
create table staffs(Staff_id int,First_name text,Last_name text,Phone bigint,Email text,Phone bigint,
Active int,Store_id int,Manager_id text);
create table stocks(Store_id int,Product_id int,Quantity int);
create table stores(Store_id int,Store_name text,Phone bigint,Email text,Street text,City text,
State text,Zip_code int);

select * from retail.brands;
select * from retail.categories;
select * from retail.customers;
select * from retail.order_items;
select * from retail.orders;
select * from retail.products;
select * from retail.staffs;
select * from retail.stocks;
select * from retail.stores;

select o.order_id as order_id,o.customer_id as customer_id,o.order_status as order_status,p.product_id as product_id,p.category_id as category_id from retail.orders as o
join retail.order_items as oi
on o.order_id = oi.order_id
join retail.products as p
on p.product_id = oi.product_id;

-- Total Sales by Store  o Write a query to group sales (total_price) by each store_id.
select  sum(oi.total_price) as total_price,o.store_id as store_id from retail.orders as o
join retail.order_items as oi
on o.order_id=oi.order_id
group by store_id;


-- Top 5 Selling Products
-- o Use ORDER BY and LIMIT to get the top 5 most sold products by quantity.

select p.product_id as product_id,sum(oi.quantity)as total_quantity from retail.order_items as oi
join retail.products as p
on p.product_id = oi.product_id
group by product_id
order by total_quantity desc
limit 5;

-- Customer Purchase Summary
-- o For each customer, return total orders placed, total items purchased, and total revenue.

select o.customer_id as customer_id,count(distinct(oi.order_id)) as order_placed,sum(oi.quantity)as purchased ,sum(oi.total_price) as total_revenue from retail.order_items as oi
join retail.orders as o
on o.order_id=oi.order_id
group by customer_id;

-- Segment Customers by Total Spend
-- o Write a query to classify customers into spending brackets (e.g., low, medium, high).

select customer_id ,sum(oi.total_price) as total_spend,
case
when sum(oi.total_price) <=10000 then "low"
when sum(oi.total_price)<=35000 then "medium"
else "high" 
end as customer_status
from retail.order_items as oi
join retail.orders as o
on o.order_id=oi.order_id
group by customer_id;

-- Staff Performance Analysis  
-- o Analyze total revenue generated by each staff member based on their  handled orders

select s.staff_id as staff_id,sum(oi.total_price) as total_revenue from retail.orders as o
join retail.order_items as oi
on o.order_id =oi.order_id
join retail.staffs as s
on o.staff_id=s.staff_id
group by staff_id;


-- Stock Alert Query  
-- o Write a query to list products where stock quantity < 10 in any store.  

select p.product_name as product_name,sum(sto.quantity ) as stock_quantity,st.store_name as store_name from retail.stocks as sto
join retail.products as p
on sto.product_id=p.product_id
join retail.stores as st
on sto.store_id=st.store_id
group by product_name,store_name
having sum(sto.quantity ) < 10;

-- To Create Final Segmentation Table 
CREATE TABLE customer_segments (
    customer_id INT PRIMARY KEY,
    recency INT,
    frequency INT,
    monetary DOUBLE,
    segment_label TEXT);
select * from retail.customer_segments;